services:
#  app:
#    image: docker-go:latest
#    build:
#      context: ../.
#      dockerfile: ./_build/Dockerfile
#    container_name: app
#    volumes:
#      - ../:/usr/src/app
#    depends_on:
#      - db
  db:
    image: postgres:17.0-bookworm
    container_name: pgdb
    env_file:
      - ../.env
    volumes:
      - ../scripts/db/1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - "5432:5432"
